AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Events storage app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Parameters:
  MongoDBConnectionString:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /EventsStorage/MongoDBConnectionString 

Resources:
  ProcessFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: process/
      Handler: app.process
      Runtime: python3.6
      Environment:
        Variables:
          MongoDBConnectionString: !Ref MongoDBConnectionString
      Events:
        ProcessTrigger:
          Type: SQS # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Queue: !GetAtt ProcessQueue.Arn
            VisibilityTimeout: 60 # 1 minute
            MessageRetentionPeriod: 300 # 5 mins.

  ProcessQueue:
    Type: AWS::SQS::Queue
